// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1.DAL.Context;

namespace _1.DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221122081104_111111111")]
    partial class _111111111
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_1.DAL.Models.chatLieu", b =>
                {
                    b.Property<string>("maChatLieu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("IdChatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tenCL")
                        .IsRequired()
                        .HasColumnName("tenCL")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("trangThai")
                        .HasColumnName("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("maChatLieu");

                    b.ToTable("chatLieu");
                });

            modelBuilder.Entity("_1.DAL.Models.chucVu", b =>
                {
                    b.Property<string>("maChucVu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("IDchucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tenCV")
                        .IsRequired()
                        .HasColumnName("tenCV")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("maChucVu");

                    b.ToTable("chucVu");
                });

            modelBuilder.Entity("_1.DAL.Models.hangSX", b =>
                {
                    b.Property<string>("maHangSX")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("IdHangSX")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tenHangSX")
                        .IsRequired()
                        .HasColumnName("tenHangSX")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("trangThai")
                        .HasColumnName("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("maHangSX");

                    b.ToTable("hangSX");
                });

            modelBuilder.Entity("_1.DAL.Models.hoaDon", b =>
                {
                    b.Property<string>("maHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("IdHD")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SDT_KH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("maNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ngayBan")
                        .HasColumnName("ngayBan")
                        .HasColumnType("date");

                    b.Property<DateTime>("ngayTT")
                        .HasColumnName("ngayTT")
                        .HasColumnType("date");

                    b.Property<bool>("trangThai")
                        .HasColumnName("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("maHoaDon");

                    b.HasIndex("SDT_KH");

                    b.HasIndex("maNhanVien");

                    b.ToTable("hoaDon");
                });

            modelBuilder.Entity("_1.DAL.Models.hoaDonChiTiet", b =>
                {
                    b.Property<string>("maHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("maSanPhamChiTiet")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Soluong")
                        .HasColumnName("Soluong")
                        .HasColumnType("int");

                    b.Property<bool>("Trangthai")
                        .HasColumnName("trangThai")
                        .HasColumnType("bit");

                    b.Property<int>("donGia")
                        .HasColumnName("donGia")
                        .HasColumnType("int");

                    b.HasKey("maHoaDon", "maSanPhamChiTiet");

                    b.HasIndex("maSanPhamChiTiet");

                    b.ToTable("hoaDonChiTiet");
                });

            modelBuilder.Entity("_1.DAL.Models.khachHang", b =>
                {
                    b.Property<string>("SDT_KH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnName("TenKH")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("diaChi")
                        .IsRequired()
                        .HasColumnName("diaChi")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("gioiTinh")
                        .HasColumnName("gioiTinh")
                        .HasColumnType("bit");

                    b.Property<bool>("trangThai")
                        .HasColumnName("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("SDT_KH");

                    b.ToTable("khachHang");
                });

            modelBuilder.Entity("_1.DAL.Models.mauSac", b =>
                {
                    b.Property<string>("maMauSac")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("IdMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tenMau")
                        .IsRequired()
                        .HasColumnName("tenMau")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("trangThai")
                        .HasColumnName("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("maMauSac");

                    b.ToTable("mauSac");
                });

            modelBuilder.Entity("_1.DAL.Models.nhanVien", b =>
                {
                    b.Property<string>("maNhanVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("IdNV")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnName("SDT")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnName("TenNV")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("diaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("maChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("matKhau")
                        .IsRequired()
                        .HasColumnName("matKhau")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("tinhTrang")
                        .HasColumnName("tinhTrang")
                        .HasColumnType("bit");

                    b.HasKey("maNhanVien");

                    b.HasIndex("maChucVu");

                    b.ToTable("nhanVien");
                });

            modelBuilder.Entity("_1.DAL.Models.sanPham", b =>
                {
                    b.Property<string>("maSanPham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("IdSP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasColumnName("TenSP")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("trangThai")
                        .HasColumnName("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("maSanPham");

                    b.ToTable("Sanpham");
                });

            modelBuilder.Entity("_1.DAL.Models.sanPhamChiTiet", b =>
                {
                    b.Property<string>("maSanPhamChiTiet")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Giaban")
                        .HasColumnType("int");

                    b.Property<int>("Gianhap")
                        .HasColumnType("int");

                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.Property<string>("maChatLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("maHangSX")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("maMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("maSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("maSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("maSanPhamChiTiet");

                    b.HasIndex("maChatLieu");

                    b.HasIndex("maHangSX");

                    b.HasIndex("maMauSac");

                    b.HasIndex("maSanPham");

                    b.HasIndex("maSize");

                    b.ToTable("sanPhamChiTiet");
                });

            modelBuilder.Entity("_1.DAL.Models.size", b =>
                {
                    b.Property<string>("maSize")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("IdSize")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SiZe")
                        .IsRequired()
                        .HasColumnName("SiZe")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("trangThai")
                        .HasColumnName("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("maSize");

                    b.ToTable("size");
                });

            modelBuilder.Entity("_1.DAL.Models.hoaDon", b =>
                {
                    b.HasOne("_1.DAL.Models.khachHang", "khachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("SDT_KH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.nhanVien", "nhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("maNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_1.DAL.Models.hoaDonChiTiet", b =>
                {
                    b.HasOne("_1.DAL.Models.hoaDon", "hoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("maHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.sanPhamChiTiet", "sanPhamChiTiet")
                        .WithMany("hoaDonChiTiet")
                        .HasForeignKey("maSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_1.DAL.Models.nhanVien", b =>
                {
                    b.HasOne("_1.DAL.Models.chucVu", "chucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("maChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_1.DAL.Models.sanPhamChiTiet", b =>
                {
                    b.HasOne("_1.DAL.Models.chatLieu", "chatLieu")
                        .WithMany("SanphamChitietss")
                        .HasForeignKey("maChatLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.hangSX", "hangSX")
                        .WithMany("SanphamChitietss")
                        .HasForeignKey("maHangSX")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.mauSac", "mauSac")
                        .WithMany("SanphamChitietss")
                        .HasForeignKey("maMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.sanPham", "sanPham")
                        .WithMany("sanPhamChiTiets")
                        .HasForeignKey("maSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.size", "size")
                        .WithMany("SanphamChitietss")
                        .HasForeignKey("maSize")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
