// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1.DAL.Context;

#nullable disable

namespace _1.DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221129170811_111")]
    partial class _111
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_1.DAL.Models.chucVu", b =>
                {
                    b.Property<int>("maChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("maChucVu"), 1L, 1);

                    b.Property<string>("tenCV")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenCV");

                    b.HasKey("maChucVu");

                    b.ToTable("chucVu", (string)null);

                    b.HasData(
                        new
                        {
                            maChucVu = 1,
                            tenCV = "Quản lý"
                        },
                        new
                        {
                            maChucVu = 2,
                            tenCV = "Nhân viên"
                        });
                });

            modelBuilder.Entity("_1.DAL.Models.hangSX", b =>
                {
                    b.Property<int>("maHangSX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("maHangSX"), 1L, 1);

                    b.Property<string>("tenHangSX")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenHangSX");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trangThai");

                    b.HasKey("maHangSX");

                    b.ToTable("hangSX", (string)null);

                    b.HasData(
                        new
                        {
                            maHangSX = 1,
                            tenHangSX = "Sao Vàng",
                            trangThai = true
                        },
                        new
                        {
                            maHangSX = 2,
                            tenHangSX = "Sahara",
                            trangThai = true
                        },
                        new
                        {
                            maHangSX = 3,
                            tenHangSX = "Tỷ Xuân",
                            trangThai = true
                        });
                });

            modelBuilder.Entity("_1.DAL.Models.hoaDon", b =>
                {
                    b.Property<int>("maHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("maHoaDon"), 1L, 1);

                    b.Property<string>("SDT_KH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("maNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayBan")
                        .HasColumnType("date")
                        .HasColumnName("ngayBan");

                    b.Property<DateTime>("ngayTT")
                        .HasColumnType("date")
                        .HasColumnName("ngayTT");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit")
                        .HasColumnName("Trangthai");

                    b.HasKey("maHoaDon");

                    b.HasIndex("SDT_KH");

                    b.HasIndex("maNhanVien");

                    b.ToTable("hoaDon", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.hoaDonChiTiet", b =>
                {
                    b.Property<int>("maHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("maSanPham")
                        .HasColumnType("int");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("Soluong");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("trangThai");

                    b.Property<int>("donGia")
                        .HasColumnType("int")
                        .HasColumnName("donGia");

                    b.HasKey("maHoaDon", "maSanPham");

                    b.HasIndex("maSanPham");

                    b.ToTable("hoaDonChiTiet", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.khachHang", b =>
                {
                    b.Property<string>("SDT_KH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenKH");

                    b.Property<string>("diaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("diaChi");

                    b.Property<bool>("gioiTinh")
                        .HasColumnType("bit")
                        .HasColumnName("gioiTinh");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trangThai");

                    b.HasKey("SDT_KH");

                    b.ToTable("khachHang", (string)null);

                    b.HasData(
                        new
                        {
                            SDT_KH = "0123456789",
                            TenKH = "Nguyễn Văn A",
                            diaChi = "Hà Nội",
                            gioiTinh = true,
                            trangThai = true
                        },
                        new
                        {
                            SDT_KH = "0123456567",
                            TenKH = "Nguyễn Văn B",
                            diaChi = "Hải Phòng",
                            gioiTinh = false,
                            trangThai = true
                        },
                        new
                        {
                            SDT_KH = "0123456678",
                            TenKH = "Nguyễn Văn C",
                            diaChi = "Lạng Sơn",
                            gioiTinh = true,
                            trangThai = true
                        });
                });

            modelBuilder.Entity("_1.DAL.Models.mauSac", b =>
                {
                    b.Property<int>("maMauSac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("maMauSac"), 1L, 1);

                    b.Property<string>("tenMau")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenMau");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trangThai");

                    b.HasKey("maMauSac");

                    b.ToTable("mauSac", (string)null);

                    b.HasData(
                        new
                        {
                            maMauSac = 1,
                            tenMau = "Xanh",
                            trangThai = true
                        },
                        new
                        {
                            maMauSac = 2,
                            tenMau = "Đỏ",
                            trangThai = true
                        },
                        new
                        {
                            maMauSac = 3,
                            tenMau = "Trắng",
                            trangThai = true
                        });
                });

            modelBuilder.Entity("_1.DAL.Models.nhanVien", b =>
                {
                    b.Property<int>("maNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("maNhanVien"), 1L, 1);

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNV");

                    b.Property<string>("diaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("maChucVu")
                        .HasColumnType("int");

                    b.Property<string>("matKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("matKhau");

                    b.Property<bool>("tinhTrang")
                        .HasColumnType("bit")
                        .HasColumnName("tinhTrang");

                    b.HasKey("maNhanVien");

                    b.HasIndex("maChucVu");

                    b.ToTable("nhanVien", (string)null);

                    b.HasData(
                        new
                        {
                            maNhanVien = 1,
                            SDT = "0379702133",
                            TenNV = "Nguyễn Văn Đạo",
                            diaChi = "Tuyên Quang",
                            email = "daonvph18705@gmail.com",
                            maChucVu = 1,
                            matKhau = "123",
                            tinhTrang = true
                        },
                        new
                        {
                            maNhanVien = 2,
                            SDT = "0379702144",
                            TenNV = "Nguyễn Văn B",
                            diaChi = "Hà Nội",
                            email = "baaa@gmail.com",
                            maChucVu = 2,
                            matKhau = "123",
                            tinhTrang = true
                        });
                });

            modelBuilder.Entity("_1.DAL.Models.SanPham", b =>
                {
                    b.Property<int>("maSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("maSanPham"), 1L, 1);

                    b.Property<decimal>("Giaban")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Gianhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.Property<string>("linkAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maHangSX")
                        .HasColumnType("int");

                    b.Property<int>("maMauSac")
                        .HasColumnType("int");

                    b.Property<int>("maSize")
                        .HasColumnType("int");

                    b.HasKey("maSanPham");

                    b.HasIndex("maHangSX");

                    b.HasIndex("maMauSac");

                    b.HasIndex("maSize");

                    b.ToTable("sanPham", (string)null);

                    b.HasData(
                        new
                        {
                            maSanPham = 1,
                            Giaban = 1500m,
                            Gianhap = 1000m,
                            Soluong = 1000,
                            TenSP = "Lacoste",
                            Trangthai = true,
                            linkAnh = "",
                            maHangSX = 1,
                            maMauSac = 1,
                            maSize = 1
                        },
                        new
                        {
                            maSanPham = 2,
                            Giaban = 2000m,
                            Gianhap = 1500m,
                            Soluong = 1200,
                            TenSP = "Gucci",
                            Trangthai = true,
                            linkAnh = "",
                            maHangSX = 2,
                            maMauSac = 2,
                            maSize = 2
                        },
                        new
                        {
                            maSanPham = 3,
                            Giaban = 1700m,
                            Gianhap = 1200m,
                            Soluong = 1300,
                            TenSP = "ADLV",
                            Trangthai = true,
                            linkAnh = "",
                            maHangSX = 3,
                            maMauSac = 3,
                            maSize = 3
                        },
                        new
                        {
                            maSanPham = 4,
                            Giaban = 2100m,
                            Gianhap = 1600m,
                            Soluong = 1400,
                            TenSP = "Uniqlo",
                            Trangthai = true,
                            linkAnh = "",
                            maHangSX = 2,
                            maMauSac = 3,
                            maSize = 1
                        });
                });

            modelBuilder.Entity("_1.DAL.Models.size", b =>
                {
                    b.Property<int>("maSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("maSize"), 1L, 1);

                    b.Property<string>("SiZe")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SiZe");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trangThai");

                    b.HasKey("maSize");

                    b.ToTable("size", (string)null);

                    b.HasData(
                        new
                        {
                            maSize = 1,
                            SiZe = "M",
                            trangThai = true
                        },
                        new
                        {
                            maSize = 2,
                            SiZe = "L",
                            trangThai = true
                        },
                        new
                        {
                            maSize = 3,
                            SiZe = "XL",
                            trangThai = true
                        });
                });

            modelBuilder.Entity("_1.DAL.Models.hoaDon", b =>
                {
                    b.HasOne("_1.DAL.Models.khachHang", "khachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("SDT_KH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.nhanVien", "nhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("maNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("khachHang");

                    b.Navigation("nhanVien");
                });

            modelBuilder.Entity("_1.DAL.Models.hoaDonChiTiet", b =>
                {
                    b.HasOne("_1.DAL.Models.hoaDon", "hoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("maHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.SanPham", "sanPham")
                        .WithMany("hoaDonChiTiet")
                        .HasForeignKey("maSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hoaDon");

                    b.Navigation("sanPham");
                });

            modelBuilder.Entity("_1.DAL.Models.nhanVien", b =>
                {
                    b.HasOne("_1.DAL.Models.chucVu", "chucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("maChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chucVu");
                });

            modelBuilder.Entity("_1.DAL.Models.SanPham", b =>
                {
                    b.HasOne("_1.DAL.Models.hangSX", "hangSX")
                        .WithMany("SanphamChitietss")
                        .HasForeignKey("maHangSX")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.mauSac", "mauSac")
                        .WithMany("SanphamChitietss")
                        .HasForeignKey("maMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.size", "size")
                        .WithMany("SanphamChitietss")
                        .HasForeignKey("maSize")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hangSX");

                    b.Navigation("mauSac");

                    b.Navigation("size");
                });

            modelBuilder.Entity("_1.DAL.Models.chucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("_1.DAL.Models.hangSX", b =>
                {
                    b.Navigation("SanphamChitietss");
                });

            modelBuilder.Entity("_1.DAL.Models.hoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("_1.DAL.Models.khachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("_1.DAL.Models.mauSac", b =>
                {
                    b.Navigation("SanphamChitietss");
                });

            modelBuilder.Entity("_1.DAL.Models.nhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("_1.DAL.Models.SanPham", b =>
                {
                    b.Navigation("hoaDonChiTiet");
                });

            modelBuilder.Entity("_1.DAL.Models.size", b =>
                {
                    b.Navigation("SanphamChitietss");
                });
#pragma warning restore 612, 618
        }
    }
}
